[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
vault = "Csj4WkNPZa7wtoT8yrxLPouB98gprmY2CgoKETntzEUW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/cipher-crypto/.config/solana/id.json"

[scripts]
vault = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
